# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3xwords-setup-window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# This file was generated by piuic5 from a .ui file. The code has been used
# in 3xwords.py.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setupWindow(object):
    def setupUi(self, setupWindow):
        setupWindow.setObjectName("setupWindow")
        setupWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        setupWindow.resize(800, 170)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(setupWindow.sizePolicy().hasHeightForWidth())
        setupWindow.setSizePolicy(sizePolicy)
        setupWindow.setMinimumSize(QtCore.QSize(800, 170))
        setupWindow.setMaximumSize(QtCore.QSize(800, 170))
        self.gridLayout = QtWidgets.QGridLayout(setupWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.repoNameLabel = QtWidgets.QLabel(setupWindow)
        self.repoNameLabel.setObjectName("repoNameLabel")
        self.gridLayout.addWidget(self.repoNameLabel, 2, 0, 1, 1)
        self.repoLinkLabel = QtWidgets.QLabel(setupWindow)
        self.repoLinkLabel.setObjectName("repoLinkLabel")
        self.gridLayout.addWidget(self.repoLinkLabel, 0, 0, 1, 1)
        self.repoNameLineEdit = QtWidgets.QLineEdit(setupWindow)
        self.repoNameLineEdit.setObjectName("repoNameLineEdit")
        self.gridLayout.addWidget(self.repoNameLineEdit, 3, 0, 1, 1)
        self.repoLinkLineEdit = QtWidgets.QLineEdit(setupWindow)
        self.repoLinkLineEdit.setObjectName("repoLinkLineEdit")
        self.gridLayout.addWidget(self.repoLinkLineEdit, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(setupWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)

        self.retranslateUi(setupWindow)
        self.buttonBox.accepted.connect(setupWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(setupWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(setupWindow)

    def retranslateUi(self, setupWindow):
        _translate = QtCore.QCoreApplication.translate
        setupWindow.setWindowTitle(_translate("setupWindow", "Setup Window"))
        self.repoNameLabel.setText(_translate("setupWindow", "Repository Name"))
        self.repoLinkLabel.setText(_translate("setupWindow", "Repository Web URL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    setupWindow = QtWidgets.QDialog()
    ui = Ui_setupWindow()
    ui.setupUi(setupWindow)
    setupWindow.show()
    sys.exit(app.exec_())
